[package]
name = "bevy_mod_ouroboros"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
futures-util = "0.3.21"
num_enum = "0.5.7"
quinn = "0.8.3"
rcgen = "0.9.2"
rustls = "0.20.6"
tokio = "1.19.2"