[package]
name = "ouroboros_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ouroboros_common]
path = "../common"

[dependencies]
bevy_egui = "0.14.0"